twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        timezone: America/Vancouver
        format: Y-m-d h:m:s
        interval_format: '%%d days'
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - "@NinesUtil/form/fields.html.twig"
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'jquery.collection.html.twig'
    globals:
        text_service: '@Nines\UtilBundle\Services\Text'
        comment_service: '@Nines\FeedbackBundle\Services\CommentService'
        nines_editor_config: js/editor-config.js
        piwik_enabled: '%dhil.piwik_enabled%'
        piwik_url: '%dhil.piwik_url%'
        piwik_siteid: '%dhil.piwik_siteid%'
        piwik_domain: '%dhil.piwik_domain%'
