<?php

namespace AppBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
          public function typeaheadQuery($q) {
              $qb = $this->createQueryBuilder('e');
              $qb->andWhere("e.name LIKE :q");
              $qb->orderBy('e.name');
              $qb->setParameter('q', "{$q}%");
              return $qb->getQuery()->execute();
          }
}
