<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LedgerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LedgerRepository extends EntityRepository {
        public function typeaheadQuery($q) {
            $qb = $this->createQueryBuilder('e');
            $qb->innerJoin('e.notary', 'n');
            $qb->andWhere("n.name LIKE :q");
            $qb->orderBy('n.name');
            $qb->orderBY('e.year');
            $qb->setParameter('q', "{$q}%");
            return $qb->getQuery()->execute();
        }
}
