<?php

namespace AppBundle\Repository;

/**
 * LedgerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LedgerRepository extends \Doctrine\ORM\EntityRepository {

}
