<?php

namespace AppBundle\Repository;

/**
 * LocationCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
