<?php

namespace AppBundle\Repository;

/**
 * NotaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaryRepository extends \Doctrine\ORM\EntityRepository
{

}
