<?php

namespace AppBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository {

    public function typeaheadQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->andWhere("e.firstName LIKE :q");
        $qb->orWhere("e.lastName LIKE :q");
        $qb->orderBy('e.lastName');
        $qb->addOrderBy('e.firstName');
        $qb->setParameter('q', "{$q}%");
        return $qb->getQuery()->execute();
    }

    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->andWhere('MATCH(e.firstName,e.lastName) AGAINST (:q BOOLEAN) > 0');
        $qb->setParameter('q', $q);
        return $qb->getQuery();
    }
}
