<?php

namespace AppBundle\Repository;

/**
 * RelationshipCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationshipCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
