<?php

namespace AppBundle\Repository;

/**
 * WitnessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WitnessRepository extends \Doctrine\ORM\EntityRepository
{

}
