<?php

namespace AppBundle\Repository;

/**
 * WitnessCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WitnessCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
